### ISSUE TITLE
[discussion] transform caching.

### ISSUE THREAD

**Issue by trusktr** [infamous/motor#2]
Should we cache transforms on nested DOM elements?

**Comment by pandafinity** [comment]
What would you need to know if someone uses the Browsers 'back' button action?  Would the cache help to know what State you need to get back to?

**Comment by trusktr** [comment]
The "cache" I'm talking about here is for storing matrix transforms that determine where things are rendered in 3D space. You're talking about "[URL routing](https://www.google.com/#q=url%20routing)", using tools like [flow-router](https://github.com/kadirahq/flow-router), [react-router](https://github.com/rackt/react-router), [ui-router](https://github.com/angular-ui/ui-router/wiki/URL-Routing), etc. Those run completely independently of infamous/motor, with or without infamous/motor. When a route changes you can (using one of those libraries) tell infamous/motor to render something, for example. :)

**Comment by trusktr** [comment]
Closing in favor of discussing at forums.infamous.io.

**Comment by pandafinity** [comment]
Hi - Appreciate this is closed but I wanted to say I didn't explain it properly as I feel you misunderstood me.

I did not mean URL Routing, but in reference to transitions and transformations - a 'State History' of what the element looked like, what it 'did' at that specific point of User interaction.  Like having an abstracted transition list of 3d space, where you know the sequence based on the Element's 'workflow'..

Didn't know whether I should add this in the forum as it was more a clarification :)

Hope you had a good weekend.

**Comment by trusktr** [comment]
@pandafinity Ah, I see what you mean. I think this can be a separate layer on top of our new engine. There's various ways in the community to keep track of history state changes, for example here's a simple example of how you might do it in React: https://gist.github.com/ericflo/9405239.

Here's a library for doing it in Meteor: https://github.com/JackAdams/meteor-transactions

So, in general, I think these type of state things are something that should be implemented outside of the library we're making here.

We are also considering things like having a `Timeline` in our library, in which case it would be easy to go to a previous state of animation.

And of course, those things can be controlled with URL routing too. :}

**Comment by trusktr** [comment]
Definitely feel free to open up discussions like this on the forums though, it's completely valid. :}
